name: Update README

on:
  schedule:
    - cron: '0 0 * * *' # 每天午夜运行
  workflow_dispatch: # 允许手动触发

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Fetch download stats
        run: |
          curl -s https://jitpack.io/api/downloads/com.github.zimoyin/autojs_kotlin_sdk > stats.json
          WEEK=$(jq '.week' stats.json)
          MONTH=$(jq '.month' stats.json)
          sed -i "s/周下载：.*/周下载：$WEEK/" README.md
          sed -i "s/月下载：.*/月下载：$MONTH/" README.md

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add README.md
          git status # 查看变动的文件
          git commit -m "Update download stats" || echo "No changes to commit"
          git push
